### ISSUE TITLE
Dashboard FRONT

### ISSUE THREAD

**Issue by Matthieu28** [WildCodeSchool/0523-RemFr-JavaAngular-P2-frontend-myserieslib#44]
```[tasklist]
### Tasks
- [ ] Category and Main dashboard - Huy
- [ ] Edit and delete in Series List dashboard
- [ ] Add search and delete
- [ ] Add series dashboard connect back
```
